openapi: 3.0.3
info:
  title: Accounting API
  version: 1.0.0
servers:
  - url: http:localhost:{port}/{basePath}
    description: テストサーバー
    variables:
      port:
        default: "4010"
      basePath:
        default: api/v1
tags:
  - name: 検索
    description: search
  - name: 勘定科目
    description: accounts
  - name: 部門
    description: departments
  - name: セグメント
    description: segments
paths:
  /search/total:
    get:
      tags:
        - 検索
      operationId: search-total
      description: 全文検索API。`/search`は100件以上のヒットでエラーを返すため事前にこちらのエンドポイントで件数を取得する必要があります
      parameters:
        - name: resource
          description: 対象のリソースをカンマ区切りで記載します
          in: query
          required: true
          schema:
            type: string
            example: account,department
        - name: q
          description: 検索文字列
          in: query
          required: false
          schema:
            type: string
            example: 現金
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - total
                properties:
                  total:
                    type: integer
                    format: int32
                    minimum: 0
                    maximum: 110
                    example: 1
        "400":
          description: Invalid status value
  /search:
    get:
      tags:
        - 検索
      operationId: search
      description: 全文検索API。100件以上ヒットした場合はエラーを返すため事前に`/search/total`で件数を確認してください
      parameters:
        - name: resource
          description: 対象のリソースをカンマ区切りで記載します
          in: query
          required: true
          schema:
            type: string
            example: account,department
        - name: q
          description: 検索文字列
          in: query
          required: false
          schema:
            type: string
            example: 当座預金
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                  - total
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required:
                        - resource
                        - id
                        - name
                      properties:
                        resource:
                          type: string
                          enum:
                            - account
                            - department
                            - segment
                          example: account
                        id:
                          type: integer
                          format: int32
                          minimum: 0
                          example: 5
                        name:
                          type: string
                          minLength: 2
                          maxLength: 16
                          example: 建物
                  total:
                    type: integer
                    format: int32
                    minimum: 0
                    maximum: 100
                    example: 1
        "400":
          description: Invalid status value
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - total
                properties:
                  error:
                    type: string
                    example: too match
                  total:
                    type: integer
                    format: int32
                    minimum: 0
                    example: 128
  /companies/{id}/accounts:
    get:
      tags:
        - 勘定科目
      operationId: accounts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Account"
                  total:
                    type: number
                    format: int32
                    minimum: 0
                    example: 1
        "400":
          description: Invalid status value
  /companies/{id}/departments:
    get:
      tags:
        - 部門
      operationId: departments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Department"
                  total:
                    type: number
                    format: int32
                    minimum: 0
                    example: 1
        "400":
          description: Invalid status value
  /companies/{id}/segments:
    get:
      tags:
        - セグメント
      operationId: segments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 1
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Segment"
                  total:
                    type: number
                    format: int32
                    minimum: 0
                    example: 1
        "400":
          description: Invalid status value
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          example: 1
        name:
          type: string
          example: "現金"
        companyId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        companyName:
          type: string
          example: "会社A"
        categoryId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        categoryName:
          type: string
          example: "現金及び預金"
    Department:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          example: 2
        name:
          type: string
          example: "部門B"
        companyId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        companyName:
          type: string
          example: "会社A"
        parentId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        parentName:
          type: string
          example: "部門A"
    Segment:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          example: 2
        name:
          type: string
          example: "セグメントB"
        companyId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        companyName:
          type: string
          example: "会社A"
        parentId:
          type: integer
          format: int32
          minimum: 1
          example: 1
        parentName:
          type: string
          example: "セグメントA"
